[package]
name = "fpga-gnw-romgenerator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guard = "0.5.1"
resvg = "0.32.0"
svg = "0.13.1"
